### ISSUE TITLE
Update suggested Docker images

### ISSUE THREAD

**Issue by ruksi** [valohai/valohai-cli#28]
Although all the Docker images suggested by the Valohai command-line client do work, we have newer images available that should be mentioned.

Extra points if cli fetches this information remotely.

**Comment by akx** [comment]
It probably won't be safe to directly use the image statistics data, since there are bound to be secret-by-obscurity images people use.

What if we maintain this as a [GitHub repo like GitHub itself does with gitignores](https://github.com/github/gitignore) and download it like [e.g. the `gitignore` Node client does](https://github.com/msfeldstein/gitignore/blob/1fd930645abd20a69bfb912097f3a2489567b2a0/lib/library.js)?

**Comment by ruksi** [comment]
yup, that would work! great idea

**Comment by akx** [comment]
Consider it done! https://github.com/valohai/images is the repo.

There'll be an ops PR soon too, so Peon image building will also read the remote file.
